import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { getCommandContents } from '../../../src/core/shared/skill-generation.js';
import { ALL_WORKFLOWS } from '../../../src/core/profiles.js';
import {
  CommandAdapterRegistry,
  DEFAULT_COMMAND_NAMESPACE,
  formatCommandInvocation,
  generateCommand,
  getInvocationForAdapter,
} from '../../../src/core/command-generation/index.js';

interface AdapterParityRecord {
  pathVectorSha256: string;
  invocationVectorSha256: string;
  fileContentVectorSha256: string;
}

interface ParityFixture {
  schemaVersion: number;
  sourceRevision: string;
  commands: string[];
  adapters: Record<string, AdapterParityRecord>;
}

const fixture = JSON.parse(
  readFileSync(
    new URL('../../fixtures/command-generation/pre-namespace-opsx-parity.json', import.meta.url),
    'utf8'
  )
) as ParityFixture;

function hashVector(values: string[]): string {
  const hash = createHash('sha256');
  for (const value of values) {
    const bytes = Buffer.from(value, 'utf8');
    const length = Buffer.allocUnsafe(4);
    length.writeUInt32BE(bytes.length);
    hash.update(length);
    hash.update(bytes);
  }
  return hash.digest('hex');
}

const commands = getCommandContents(ALL_WORKFLOWS);
const adapters = CommandAdapterRegistry.getAll()
  .slice()
  .sort((a, b) => a.toolId.localeCompare(b.toolId));

describe('pre-namespace OpenSpec command parity', () => {
  it('pins the historical baseline and complete registry dimensions', () => {
    expect(fixture.schemaVersion).toBe(1);
    expect(fixture.sourceRevision).toBe('9c4021fa59ca87114ef91947e927937b406c0004');
    expect(commands.map((command) => command.id)).toEqual(fixture.commands);
    expect(commands.every((command) => command.namespace === undefined)).toBe(true);
    expect(adapters.map((adapter) => adapter.toolId)).toEqual(Object.keys(fixture.adapters));
    expect(commands).toHaveLength(12);
    expect(adapters).toHaveLength(28);
  });

  for (const adapter of adapters) {
    it(`preserves paths, invocations, and exact generated bytes for ${adapter.toolId}`, () => {
      const generated = commands.map((content) => generateCommand(content, adapter));
      const invocations = commands.map((content) =>
        formatCommandInvocation(
          getInvocationForAdapter(adapter, {
            namespace: DEFAULT_COMMAND_NAMESPACE,
            id: content.id,
          }),
          content.id,
          DEFAULT_COMMAND_NAMESPACE
        )
      );
      const actual: AdapterParityRecord = {
        pathVectorSha256: hashVector(
          generated.map((command) => command.path.split(path.sep).join('/'))
        ),
        invocationVectorSha256: hashVector(invocations),
        fileContentVectorSha256: hashVector(
          generated.map((command) => command.fileContent)
        ),
      };

      expect(actual).toEqual(fixture.adapters[adapter.toolId]);
    });
  }
});
